name: Validate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
      - name: Verify file structure
        run: |
          python -c "import os; assert os.path.exists('custom_components/wilma/__init__.py'), 'Missing __init__.py'"
          python -c "import os; assert os.path.exists('custom_components/wilma/manifest.json'), 'Missing manifest.json'"
      - name: Lint with ruff
        run: |
          ruff check .
      - name: Type check with mypy
        run: |
          mypy custom_components/wilma
      - name: Validate HACS
        uses: hacs/action@main
        with:
          category: integration
